version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.3.1

workflows:
  Welcome:
    jobs:
      - welcome/run
  build:
    steps:
        - checkout
        - *create_npmrc
        - *restore_yarn_cache
        - *yarn_install
        - *rebuild_node_sass
        - *save_yarn_cache
        - run: yarn run lint
        - run: yarn run build
