version: 2.1
jobs:
  lint:
    steps:
      - checkout
      - run: yarn install --pure-lockfile --check-files
      - run: yarn lint
  build:
    steps:
      - checkout
      - run: yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build