version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.3.1

workflows:
  Welcome:
    jobs:
      - welcome/run
  build:
    steps:
        - checkout
        - run: yarn install --pure-lockfile --no-progress --non-interactive --check-files
        - run: yarn run lint
